var searchData=
[
  ['paracommon_7048',['ParaCommon',['../classParaCommon.html',1,'']]],
  ['parakpoints_7049',['ParaKpoints',['../classParaKpoints.html',1,'']]],
  ['parallel_7050',['Parallel',['../classExx__Abfs_1_1Parallel.html',1,'Exx_Abfs']]],
  ['parallel_5fgrid_7051',['Parallel_Grid',['../classParallel__Grid.html',1,'']]],
  ['parallel_5fkpoints_7052',['Parallel_Kpoints',['../classParallel__Kpoints.html',1,'']]],
  ['parallel_5forbitals_7053',['Parallel_Orbitals',['../structParallel__Orbitals.html',1,'Parallel_Orbitals'],['../classTest__Deepks_1_1Parallel__Orbitals.html',1,'Test_Deepks::Parallel_Orbitals']]],
  ['paraprepare_7054',['ParaPrepare',['../classParaPrepare.html',1,'']]],
  ['parareduce_7055',['ParaReduce',['../classParaReduce.html',1,'']]],
  ['pca_7056',['PCA',['../classExx__Abfs_1_1PCA.html',1,'Exx_Abfs']]],
  ['polyint_7057',['PolyInt',['../classModuleBase_1_1PolyInt.html',1,'ModuleBase']]],
  ['potbase_7058',['PotBase',['../classelecstate_1_1PotBase.html',1,'elecstate']]],
  ['potefield_7059',['PotEfield',['../classelecstate_1_1PotEfield.html',1,'elecstate']]],
  ['potential_7060',['Potential',['../classelecstate_1_1Potential.html',1,'elecstate']]],
  ['potgate_7061',['PotGate',['../classelecstate_1_1PotGate.html',1,'elecstate']]],
  ['pothartree_7062',['PotHartree',['../classelecstate_1_1PotHartree.html',1,'elecstate']]],
  ['potlocal_7063',['PotLocal',['../classelecstate_1_1PotLocal.html',1,'elecstate']]],
  ['potsurchem_7064',['PotSurChem',['../classelecstate_1_1PotSurChem.html',1,'elecstate']]],
  ['potxc_7065',['PotXC',['../classelecstate_1_1PotXC.html',1,'elecstate']]],
  ['print_5finfo_7066',['Print_Info',['../classPrint__Info.html',1,'']]],
  ['pseudo_5fnc_7067',['pseudo_nc',['../classpseudo__nc.html',1,'']]],
  ['pseudopot_5fcell_5fvl_7068',['pseudopot_cell_vl',['../classpseudopot__cell__vl.html',1,'']]],
  ['pseudopot_5fcell_5fvnl_7069',['pseudopot_cell_vnl',['../classpseudopot__cell__vnl.html',1,'']]],
  ['pseudopot_5fupf_7070',['Pseudopot_upf',['../classPseudopot__upf.html',1,'']]],
  ['psi_7071',['Psi',['../classpsi_1_1Psi.html',1,'psi']]],
  ['psi_3c_20double_20_3e_7072',['Psi&lt; double &gt;',['../classpsi_1_1Psi.html',1,'psi']]],
  ['psi_3c_20double_2c_20psi_3a_3adevice_5fcpu_20_3e_7073',['Psi&lt; double, psi::DEVICE_CPU &gt;',['../classpsi_1_1Psi.html',1,'psi']]],
  ['psi_3c_20fptype_2c_20psi_3a_3adevice_5fcpu_20_3e_7074',['Psi&lt; FPTYPE, psi::DEVICE_CPU &gt;',['../classpsi_1_1Psi.html',1,'psi']]],
  ['psi_3c_20std_3a_3acomplex_3c_20double_20_3e_20_3e_7075',['Psi&lt; std::complex&lt; double &gt; &gt;',['../classpsi_1_1Psi.html',1,'psi']]],
  ['psi_3c_20std_3a_3acomplex_3c_20double_20_3e_2c_20psi_3a_3adevice_5fcpu_20_3e_7076',['Psi&lt; std::complex&lt; double &gt;, psi::DEVICE_CPU &gt;',['../classpsi_1_1Psi.html',1,'psi']]],
  ['psi_3c_20std_3a_3acomplex_3c_20fptype_20_3e_2c_20psi_3a_3adevice_5fcpu_20_3e_7077',['Psi&lt; std::complex&lt; FPTYPE &gt;, psi::DEVICE_CPU &gt;',['../classpsi_1_1Psi.html',1,'psi']]],
  ['psi_3c_20t_20_3e_7078',['Psi&lt; T &gt;',['../classpsi_1_1Psi.html',1,'psi']]],
  ['psi_3c_20t_2c_20psi_3a_3adevice_5fcpu_20_3e_7079',['Psi&lt; T, psi::DEVICE_CPU &gt;',['../classpsi_1_1Psi.html',1,'psi']]],
  ['pw_5fbasis_7080',['PW_Basis',['../classModulePW_1_1PW__Basis.html',1,'ModulePW']]],
  ['pw_5fbasis_5fbig_7081',['PW_Basis_Big',['../classModulePW_1_1PW__Basis__Big.html',1,'ModulePW']]],
  ['pw_5fbasis_5fk_7082',['PW_Basis_K',['../classModulePW_1_1PW__Basis__K.html',1,'ModulePW']]],
  ['pw_5fbasis_5fk_5fbig_7083',['PW_Basis_K_Big',['../classModulePW_1_1PW__Basis__K__Big.html',1,'ModulePW']]],
  ['pwtest_7084',['PWTEST',['../classPWTEST.html',1,'']]]
];
