var searchData=
[
  ['x_11019',['x',['../classFAtom.html#a2bb84cabbba669d803ea9c24ca011725',1,'FAtom']]],
  ['x6_11020',['x6',['../classtoolfunc.html#ae4e2449cb4c7b310e4427f0ba61146c3',1,'toolfunc']]],
  ['x7_11021',['x7',['../classtoolfunc.html#ac8d36f6766765ed1c229f14c1c96194d',1,'toolfunc']]],
  ['xc_11022',['xc',['../classXC__Functional.html#aabcb3922301e46a58defb5bb0c7d138c',1,'XC_Functional']]],
  ['xc_5ffunctional_11023',['XC_Functional',['../classXC__Functional.html#adf07b89fb5c5ce18651d572a0b7f57f2',1,'XC_Functional']]],
  ['xc_5fspin_11024',['xc_spin',['../classXC__Functional.html#a8e84b873fd30954b12e9c49f1b89d025',1,'XC_Functional']]],
  ['xc_5fspin_5flibxc_11025',['xc_spin_libxc',['../classXC__Functional.html#aed1f401fd7b4c75a28b8deb909eaa69f',1,'XC_Functional']]],
  ['xheevx_11026',['xheevx',['../classLapackConnector.html#a5f9c60453143529b6cfe9af546dff52e',1,'LapackConnector::xheevx(const int itype, const char jobz, const char range, const char uplo, const int n, std::complex&lt; float &gt; *a, const int lda, const float vl, const float vu, const int il, const int iu, const float abstol, const int m, float *w, std::complex&lt; float &gt; *z, const int ldz, std::complex&lt; float &gt; *work, const int lwork, float *rwork, int *iwork, int *ifail, int &amp;info)'],['../classLapackConnector.html#a9423ad3c04a0d92d025706de9de63664',1,'LapackConnector::xheevx(const int itype, const char jobz, const char range, const char uplo, const int n, std::complex&lt; double &gt; *a, const int lda, const double vl, const double vu, const int il, const int iu, const double abstol, const int m, double *w, std::complex&lt; double &gt; *z, const int ldz, std::complex&lt; double &gt; *work, const int lwork, double *rwork, int *iwork, int *ifail, int &amp;info)']]],
  ['xhegvd_11027',['xhegvd',['../classLapackConnector.html#af19d834023cac8b9bbf5461f0b5ec4d4',1,'LapackConnector::xhegvd(const int itype, const char jobz, const char uplo, const int n, std::complex&lt; float &gt; *a, const int lda, const std::complex&lt; float &gt; *b, const int ldb, float *w, std::complex&lt; float &gt; *work, int lwork, float *rwork, int lrwork, int *iwork, int liwork, int &amp;info)'],['../classLapackConnector.html#a454abc38dcbb848a4ed6cc06a5a8e9b1',1,'LapackConnector::xhegvd(const int itype, const char jobz, const char uplo, const int n, std::complex&lt; double &gt; *a, const int lda, const std::complex&lt; double &gt; *b, const int ldb, double *w, std::complex&lt; double &gt; *work, int lwork, double *rwork, int lrwork, int *iwork, int liwork, int &amp;info)']]],
  ['xhegvx_11028',['xhegvx',['../classLapackConnector.html#a73da45a5e09c945a3fef404ab00165d5',1,'LapackConnector::xhegvx(const int itype, const char jobz, const char range, const char uplo, const int n, const std::complex&lt; float &gt; *a, const int lda, const std::complex&lt; float &gt; *b, const int ldb, const float vl, const float vu, const int il, const int iu, const float abstol, const int m, float *w, std::complex&lt; float &gt; *z, const int ldz, std::complex&lt; float &gt; *work, const int lwork, float *rwork, int *iwork, int *ifail, int &amp;info, int nbase_x)'],['../classLapackConnector.html#a993bf8419ef4f94b581a024299bc22e6',1,'LapackConnector::xhegvx(const int itype, const char jobz, const char range, const char uplo, const int n, const std::complex&lt; double &gt; *a, const int lda, const std::complex&lt; double &gt; *b, const int ldb, const double vl, const double vu, const int il, const int iu, const double abstol, const int m, double *w, std::complex&lt; double &gt; *z, const int ldz, std::complex&lt; double &gt; *work, const int lwork, double *rwork, int *iwork, int *ifail, int &amp;info, int nbase_x)']]]
];
