var searchData=
[
  ['x_10825',['x',['../classFAtom.html#a2bb84cabbba669d803ea9c24ca011725',1,'FAtom']]],
  ['x6_10826',['x6',['../classtoolfunc.html#ae4e2449cb4c7b310e4427f0ba61146c3',1,'toolfunc']]],
  ['x7_10827',['x7',['../classtoolfunc.html#ac8d36f6766765ed1c229f14c1c96194d',1,'toolfunc']]],
  ['xc_10828',['xc',['../classXC__Functional.html#aabcb3922301e46a58defb5bb0c7d138c',1,'XC_Functional']]],
  ['xc_5ffunctional_10829',['XC_Functional',['../classXC__Functional.html#adf07b89fb5c5ce18651d572a0b7f57f2',1,'XC_Functional']]],
  ['xc_5fspin_10830',['xc_spin',['../classXC__Functional.html#a8e84b873fd30954b12e9c49f1b89d025',1,'XC_Functional']]],
  ['xc_5fspin_5flibxc_10831',['xc_spin_libxc',['../classXC__Functional.html#aed1f401fd7b4c75a28b8deb909eaa69f',1,'XC_Functional']]],
  ['xheevx_10832',['xheevx',['../classLapackConnector.html#a5c898e62cb116d514788a72e03547fa7',1,'LapackConnector::xheevx(const int itype, const char jobz, const char range, const char uplo, const int n, std::complex&lt; float &gt; *a, const int lda, const float vl, const float vu, const int il, const int iu, const float abstol, const int m, float *w, std::complex&lt; float &gt; *z, const int ldz, std::complex&lt; float &gt; *work, const int lwork, float *rwork, int *iwork, int *ifail, int info)'],['../classLapackConnector.html#a9446f4bb87830fa67846f78f4016b8aa',1,'LapackConnector::xheevx(const int itype, const char jobz, const char range, const char uplo, const int n, std::complex&lt; double &gt; *a, const int lda, const double vl, const double vu, const int il, const int iu, const double abstol, const int m, double *w, std::complex&lt; double &gt; *z, const int ldz, std::complex&lt; double &gt; *work, const int lwork, double *rwork, int *iwork, int *ifail, int info)']]],
  ['xhegvd_10833',['xhegvd',['../classLapackConnector.html#a189c411f37998aea654d7fa1c981e974',1,'LapackConnector::xhegvd(const int itype, const char jobz, const char uplo, const int n, std::complex&lt; float &gt; *a, const int lda, const std::complex&lt; float &gt; *b, const int ldb, float *w, std::complex&lt; float &gt; *work, int lwork, float *rwork, int lrwork, int *iwork, int liwork, int info)'],['../classLapackConnector.html#a945689ee89ac1d08fa873ae08677db1f',1,'LapackConnector::xhegvd(const int itype, const char jobz, const char uplo, const int n, std::complex&lt; double &gt; *a, const int lda, const std::complex&lt; double &gt; *b, const int ldb, double *w, std::complex&lt; double &gt; *work, int lwork, double *rwork, int lrwork, int *iwork, int liwork, int info)']]],
  ['xhegvx_10834',['xhegvx',['../classLapackConnector.html#ac426799f3c0f2ddc4382de052856917d',1,'LapackConnector::xhegvx(const int itype, const char jobz, const char range, const char uplo, const int n, const std::complex&lt; float &gt; *a, const int lda, const std::complex&lt; float &gt; *b, const int ldb, const float vl, const float vu, const int il, const int iu, const float abstol, const int m, float *w, std::complex&lt; float &gt; *z, const int ldz, std::complex&lt; float &gt; *work, const int lwork, float *rwork, int *iwork, int *ifail, int info, int nbase_x)'],['../classLapackConnector.html#a0e8d7c925f312113b20b96bc753c990a',1,'LapackConnector::xhegvx(const int itype, const char jobz, const char range, const char uplo, const int n, const std::complex&lt; double &gt; *a, const int lda, const std::complex&lt; double &gt; *b, const int ldb, const double vl, const double vu, const int il, const int iu, const double abstol, const int m, double *w, std::complex&lt; double &gt; *z, const int ldz, std::complex&lt; double &gt; *work, const int lwork, double *rwork, int *iwork, int *ifail, int info, int nbase_x)']]]
];
